#!/bin/python3

import os
import sys

class SinglyLinkedListNode:
    def __init__(self, node_data):
        self.data = node_data
        self.next = None

class SinglyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def insert_node(self, node_data):
        node = SinglyLinkedListNode(node_data)

        if not self.head:
            self.head = node
        else:
            self.tail.next = node


        self.tail = node

def print_singly_linked_list(node, sep, fptr):
    while node:
        fptr.write(str(node.data))

        node = node.next

        if node:
            fptr.write(sep)

# Complete the compare_lists function below.

#
# For your reference:
#
# SinglyLinkedListNode:
#     int data
#     SinglyLinkedListNode next
#
#
def compare_lists(llist1, llist2):
    node1 = llist1
    node2 = llist2
    
    if node1 is None and node2 is None:
        return 0
    else:
        while node1 and node2:
            if node1.data != node2.data:
                return 0
            
            node1 = node1.next
            node2 = node2.next
        
        if node1 is None and node2 is None:
            return 1
        else:
            return 0


if __name__ == '__main__':
