#!/bin/python3

import math
import os
import random
import re
import sys

class SinglyLinkedListNode:
    def __init__(self, node_data):
        self.data = node_data
        self.next = None

class SinglyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def insert_node(self, node_data):
        node = SinglyLinkedListNode(node_data)

        if not self.head:
            self.head = node
        else:
            self.tail.next = node


        self.tail = node

def print_singly_linked_list(node, sep, fptr):
    while node:
        fptr.write(str(node.data))

        node = node.next

        if node:
            fptr.write(sep)

# Complete the deleteNode function below.

#
# For your reference:
#
# SinglyLinkedListNode:
#     int data
#     SinglyLinkedListNode next
#
#
class Node(object):

    def __init__(self, data=None, next_node=None):
        self.data = data
        self.next = next_node


def deleteNode(head, position):
    node = head
    cur_index = 0

    if position ==0:
        head = node.next
        return head

    while cur_index < position-1:
        node = node.next
        cur_index += 1

    node1 = node.next
    node.next = node1.next
    node1.next = None

    return head
    # print(node.data)


if __name__ == '__main__':
