#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the encryption function below.
def encryption(s):
    a = math.sqrt(len(s))
    rows = math.floor(a)
    columns = math.ceil(a)
    l = []
    
    for i in range(columns):
        a = s[i::columns]
        l.append(a)
    print(l)
    res = ""
    for i in l:
        res += i + " "
    
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = encryption(s)

    fptr.write(result + '\n')

    fptr.close()
