#!/bin/python3

import math
import os
import random
import re
import sys

class SinglyLinkedListNode:
    def __init__(self, node_data):
        self.data = node_data
        self.next = None

class SinglyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def insert_node(self, node_data):
        node = SinglyLinkedListNode(node_data)

        if not self.head:
            self.head = node
        else:
            self.tail.next = node


        self.tail = node

def print_singly_linked_list(node, sep, fptr):
    while node:
        fptr.write(str(node.data))

        node = node.next

        if node:
            fptr.write(sep)

# Complete the insertNodeAtPosition function below.

#
# For your reference:
#
# SinglyLinkedListNode:
#     int data
#     SinglyLinkedListNode next
#
#
class Node(object):
    
    def __init__(self, data=None, next_node=None):
        self.data = data
        self.next = next_node

def insertNodeAtPosition(head, data, position):
    node = head
    cur_index = 0
    while cur_index < position-1:
        cur_index += 1
        node = node.next
    
    new_node = Node(data)  
    new_node.next = node.next
    node.next = new_node

    return head


if __name__ == '__main__':
