#!/bin/python3

import os
import sys

#
# Complete the cookies function below.
#
def cookies(k, A):
    count = 0
    while min(sorted(A)) < k:
        A = sorted(A)
        new_cookie_sweetness = (A[0]*1 + A[1]*2)
        A.pop(0)
        A.pop(0)
        A.append(new_cookie_sweetness)
        count += 1
        if A is None or len(A)==1:
            return -1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    A = list(map(int, input().rstrip().split()))

    result = cookies(k, A)

    fptr.write(str(result) + '\n')

    fptr.close()
