#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the palindromeIndex function below.
def is_palindrome(s):
    return s == s[::-1]

def palindromeIndex(s):
    ret = -1
    lens = len(s)
    ind = 0
    
    if is_palindrome(s):
        return ret
    
    while ind < lens//2:
        if s[ind] != s[lens-ind-1]:
            if s[ind+1] == s[lens-ind-1] and s[ind+2] == s[lens-ind-2]:
                ret = ind
                break
            else:
                ret = lens-ind-1
                break
        ind += 1
    
    return ret

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = palindromeIndex(s)

        fptr.write(str(result) + '\n')

    fptr.close()
