#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the weightedUniformStrings function below.
def weightedUniformStrings(s, queries):
    a = set(s) 
    l = []
    for i in a:
        b = 0
        score = 0
        while b != s.count(i):
            score += ord(i) - 96
            b += 1
            l.append(score)
    result = []

    for i in queries:
        if i in l:
            result.append("Yes")
        else:
            result.append("No")
    return result


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    queries_count = int(input())

    queries = []

    for _ in range(queries_count):
        queries_item = int(input())
        queries.append(queries_item)

    result = weightedUniformStrings(s, queries)

    fptr.write('\n'.join(result))
    fptr.write('\n')

    fptr.close()
